In [2]:
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential

In [3]:
from tensorflow.keras.layers import Dense

In [4]:
df=pd.read_csv("Churn_modelling.csv")

In [5]:
df


RowNumber  CustomerId         Surname  CreditScore Geography  Gender  \
0             1    15634602        Hargrave          619    France  Female   
1             2    15647311            Hill          225       NaN  Female   
2             3    15619304            Onio          629    France  Female   
3             4    15701354            Boni          699    France  Female   
4             5    15737888        Mitchell          850     Spain  Female   
5             6    15574012             Chu          645     Spain    Male   
6             7    15592531        Bartlett          619    France    Male   
7             8    15656148          Obinna          376   Germany     NaN   
8             9    15792365              He          501    France    Male   
9            10    15592389              H?          684    France    Male   
10           11    15767821          Bearce          528    France    Male   
11           12    15737173         Andrews          497     Spain    Male   
12           13    15632264             Kay          476    France  Female   
13           14    15691483            Chin          549    France  Female   
14           15    15600882           Scott          635     Spain  Female   
15           16    15643966         Goforth          616   Germany    Male   
16           17    15737452           Romeo          653   Germany    Male   
17           18    15788218       Henderson          549     Spain  Female   
18           19    15661507         Muldrow          587     Spain    Male   
19           20    15568982             Hao          726    France  Female   
20           21    15577657        McDonald          732    France    Male   
21           22    15597945        Dellucci          636     Spain  Female   
22           23    15699309       Gerasimov          510     Spain  Female   
23           24    15725737          Mosman          669    France    Male   
24           25    15625047             Yen          846    France  Female   
25           26    15738191         Maclean          577    France    Male   
26           27    15736816           Young          756   Germany    Male   
27           28    15700772         Nebechi          571    France    Male   
28           29    15728693      McWilliams          574   Germany  Female   
29           30    15656300        Lucciano          411    France    Male   
...         ...         ...             ...          ...       ...     ...   
9970       9971    15587133        Thompson          518    France    Male   
9971       9972    15721377            Chou          833    France  Female   
9972       9973    15747927           Ch'in          758    France    Male   
9973       9974    15806455          Miller          611    France    Male   
9974       9975    15695474          Barker          583    France    Male   
9975       9976    15666295           Smith          610   Germany    Male   
9976       9977    15656062         Azikiwe          637    France  Female   
9977       9978    15579969         Mancini          683    France  Female   
9978       9979    15703563           P'eng          774    France    Male   
9979       9980    15692664          Diribe          677    France  Female   
9980       9981    15719276            T'ao          741     Spain    Male   
9981       9982    15672754        Burbidge          498   Germany    Male   
9982       9983    15768163         Griffin          655   Germany  Female   
9983       9984    15656710           Cocci          613    France    Male   
9984       9985    15696175  Echezonachukwu          602   Germany    Male   
9985       9986    15586914          Nepean          659    France    Male   
9986       9987    15581736        Bartlett          673   Germany    Male   
9987       9988    15588839         Mancini          606     Spain    Male   
9988       9989    15589329         Pirozzi          775    France    Male   
9989       9990    15605622 

In [6]:
df.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography           True
Gender              True
Age                 True
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [7]:
df["Age"].mean()

38.924392439243924

In [8]:
df["Gender"].mode()[0]

'Male'

In [9]:
df["Geography"].mode()[0]

'France'

In [10]:
df["Geography"].fillna(df["Geography"].mode()[0],inplace = True)
df["Gender"].fillna(df["Gender"].mode()[0],inplace = True)
df["Age"].fillna(df["Age"].mean(),inplace = True)


In [11]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [12]:
x = df.iloc[:, 3:13]
y = df.iloc[:, 13]

In [13]:
x

CreditScore Geography  Gender        Age  Tenure    Balance  \
0             619    France  Female  42.000000       2       0.00   
1             225    France  Female  41.000000       1   83807.86   
2             629    France  Female  42.000000       8  159660.80   
3             699    France  Female  39.000000       1       0.00   
4             850     Spain  Female  43.000000       2  125510.82   
5             645     Spain    Male  44.000000       8  113755.78   
6             619    France    Male  50.000000       7       0.00   
7             376   Germany    Male  38.924392       4  115046.74   
8             501    France    Male  44.000000       4  142051.07   
9             684    France    Male  43.000000       2  134603.88   
10            528    France    Male  31.000000       6  134603.88   
11            497     Spain    Male  24.000000       3       0.00   
12            476    France  Female  34.000000      10       0.00   
13            549    France  Female  25.000000       5       0.00   
14            635     Spain  Female  35.000000       7       0.00   
15            616   Germany    Male  45.000000       3  143129.41   
16            653   Germany    Male  58.000000       1  132602.88   
17            549     Spain  Female  24.000000       9       0.00   
18            587     Spain    Male  45.000000       6       0.00   
19            726    France  Female  24.000000       6       0.00   
20            732    France    Male  41.000000       8       0.00   
21            636     Spain  Female  32.000000       8       0.00   
22            510     Spain  Female  38.000000       4       0.00   
23            669    France    Male  46.000000       3       0.00   
24            846    France  Female  38.000000       5       0.00   
25            577    France    Male  25.000000       3       0.00   
26            756   Germany    Male  36.000000       2  136815.64   
27            571    France    Male  44.000000       9       0.00   
28            574   Germany  Female  43.000000       3  141349.43   
29            411    France    Male  29.000000       0   59697.17   
...           ...       ...     ...        ...     ...        ...   
9970          518    France    Male  42.000000       7  151027.05   
9971          833    France  Female  34.000000       3  144751.81   
9972          758    France    Male  26.000000       4  155739.76   
9973          611    France    Male  27.000000       7       0.00   
9974          583    France    Male  33.000000       7  122531.86   
9975          610   Germany    Male  50.000000       1  113957.01   
9976          637    France  Female  33.000000       7  103377.81   
9977          683    France  Female  32.000000       9       0.00   
9978          774    France    Male  40.000000       9   93017.47   
9979          677    France  Female  58.000000       1   90022.85   
9980          741     Spain    Male  35.000000       6   74371.49   
9981          498   Germany    Male  42.000000       3  152039.70   
9982          655   Germany  Female  46.000000       7  137145.12   
9983          613    France    Male  40.000000       4       0.00   
9984          602   Germany    Male  35.000000       7   90602.42   
9985          659    France    Male  36.000000       6  123841.49   
9986          673   Germany    Male  47.000000       1  183579.54   
9987          606     Spain    Male  30.000000       8  180307.73   
9988          775    France    Male  30.000000       4       0.00   
9989          841     Spain    Male  28.000000       4       0.00   
9990          714   Germany    Male  33.000000       3   35016.60   
9991          597    France  Female  53.000000       4   88381.21   
9992          726     Spain    Male  36.000000       2       0.00   
9993          644    France    Male  28.000000       7  155060.41   
9994          800    France  Female  29.000000       2       0.00   
9995          771    France    Male  39.000000       5       0.00   
9996

In [18]:
y

0       1
1       0
2       1
3       0
4       0
5       1
6       0
7       1
8       0
9       0
10      0
11      0
12      0
13      0
14      0
15      0
16      1
17      0
18      0
19      0
20      0
21      0
22      1
23      0
24      0
25      0
26      0
27      0
28      0
29      0
       ..
9970    0
9971    0
9972    0
9973    0
9974    0
9975    1
9976    0
9977    0
9978    0
9979    0
9980    0
9981    1
9982    1
9983    0
9984    0
9985    0
9986    0
9987    0
9988    0
9989    0
9990    0
9991    1
9992    0
9993    0
9994    0
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [19]:
type(x)

pandas.core.frame.DataFrame

In [20]:
type(y)

pandas.core.series.Series

In [21]:
x = df.iloc[:, 3:13].values
y = df.iloc[:, 13].values

In [22]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [225, 'France', 'Female', ..., 0, 1, 112542.58],
       [629, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [14]:
y

0       1
1       0
2       1
3       0
4       0
5       1
6       0
7       1
8       0
9       0
10      0
11      0
12      0
13      0
14      0
15      0
16      1
17      0
18      0
19      0
20      0
21      0
22      1
23      0
24      0
25      0
26      0
27      0
28      0
29      0
       ..
9970    0
9971    0
9972    0
9973    0
9974    0
9975    1
9976    0
9977    0
9978    0
9979    0
9980    0
9981    1
9982    1
9983    0
9984    0
9985    0
9986    0
9987    0
9988    0
9989    0
9990    0
9991    1
9992    0
9993    0
9994    0
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [15]:
df["Geography"].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [16]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [17]:
ct = ColumnTransformer([("one",OneHotEncoder(),[1,2])],remainder = "passthrough")
x = ct.fit_transform(x)


In [18]:
x

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [19]:
x[1]

array([1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
       0.0000000e+00, 2.2500000e+02, 4.1000000e+01, 1.0000000e+00,
       8.3807860e+04, 1.0000000e+00, 0.0000000e+00, 1.0000000e+00,
       1.1254258e+05])

In [20]:
x.shape

(10000, 13)

In [21]:
df.head(25)

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  \
0           1    15634602   Hargrave          619    France  Female   
1           2    15647311       Hill          225    France  Female   
2           3    15619304       Onio          629    France  Female   
3           4    15701354       Boni          699    France  Female   
4           5    15737888   Mitchell          850     Spain  Female   
5           6    15574012        Chu          645     Spain    Male   
6           7    15592531   Bartlett          619    France    Male   
7           8    15656148     Obinna          376   Germany    Male   
8           9    15792365         He          501    France    Male   
9          10    15592389         H?          684    France    Male   
10         11    15767821     Bearce          528    France    Male   
11         12    15737173    Andrews          497     Spain    Male   
12         13    15632264        Kay          476    France  Female   
13         14    15691483       Chin          549    France  Female   
14         15    15600882      Scott          635     Spain  Female   
15         16    15643966    Goforth          616   Germany    Male   
16         17    15737452      Romeo          653   Germany    Male   
17         18    15788218  Henderson          549     Spain  Female   
18         19    15661507    Muldrow          587     Spain    Male   
19         20    15568982        Hao          726    France  Female   
20         21    15577657   McDonald          732    France    Male   
21         22    15597945   Dellucci          636     Spain  Female   
22         23    15699309  Gerasimov          510     Spain  Female   
23         24    15725737     Mosman          669    France    Male   
24         25    15625047        Yen          846    France  Female   

          Age  Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0   42.000000       2       0.00              1          1               1   
1   41.000000       1   83807.86              1          0               1   
2   42.000000       8  159660.80              3          1               0   
3   39.000000       1       0.00              2          0               0   
4   43.000000       2  125510.82              1          1               1   
5   44.000000       8  113755.78              2          1               0   
6   50.000000       7       0.00              2          1               1   
7   38.924392       4  115046.74              4          1               0   
8   44.000000       4  142051.07              2          0               1   
9   43.000000       2  134603.88              1          1               1   
10  31.000000       6  134603.88              2          0               0   
11  24.000000       3       0.00              2          1               0   
12  34.000000      10       0.00              2          1               0   
13  25.000000       5       0.00              2          0               0   
14  35.000000       7       0.00              2          1               1   
15  45.000000       3  143129.41              2          0               1   
16  58.000000       1  132602.88              1          1               0   
17  24.000000       9       0.00              2          1               1   
18  45.000000       6       0.00              1          0               0   
19  24.000000       6       0.00              2          1               1   
20  41.000000       8       0.00              2          1               1   
21  32.000000       8       0.00              2          1               0   
22  38.000000       4       0.00              1          1               0   
23  46.000000       3       0.00              2          0               1   
24  38.000000       5       0.00              1          1               1   

    EstimatedSalary  Exited  
0         101348.88       1  
1         112542.58       0  
2         113931.57       1  
3       

In [22]:
y .shape

(10000,)

In [23]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25,random_state = 0)

In [24]:
print(x.shape,"xshape")
print(y.shape,"yshape")
print(x_train.shape,"x_train shape")
print(x_test.shape,"x_test shape")
print(y_train.shape,"y_train shape")
print(y_test.shape,"y_test shape")

(10000, 13) xshape
(10000,) yshape
(8000, 13) x_train shape
(2000, 13) x_test shape
(8000,) y_train shape
(2000,) y_test shape


In [25]:
a = [1,2,3,4,5,6,7,8,9,10]
b = [11,12,13,14,15,16,17,18,19,20]

In [27]:
for i in range(5):
    a_train,a_test,b_train,b_test = train_test_split(a,b,test_size = 0.25,random_state = 47)
    print(a_train,"atrain .........")
    """print("&&&&&&&&&&&&&&&&." )
    print(b_train,"btrain .........")
    print("&&&&&&&&&&&&&&&&." )"""

[6, 4, 9, 1, 10, 7, 8] atrain .........
[6, 4, 9, 1, 10, 7, 8] atrain .........
[6, 4, 9, 1, 10, 7, 8] atrain .........
[6, 4, 9, 1, 10, 7, 8] atrain .........
[6, 4, 9, 1, 10, 7, 8] atrain .........


In [28]:
for i in range(5):
    a_train,a_test,b_train,b_test = train_test_split(a,b,test_size = 0.25)
    print(a_train,"atrain .........")
    #print("&&&&&&&&&&&&&&&&." )
    #print(b_train,"btrain .........")
    #print("&&&&&&&&&&&&&&&&." )

[8, 1, 10, 9, 5, 3, 4] atrain .........
[5, 1, 9, 10, 3, 7, 6] atrain .........
[8, 3, 5, 7, 6, 1, 2] atrain .........
[8, 3, 1, 7, 10, 9, 4] atrain .........
[8, 2, 10, 6, 3, 1, 9] atrain .........


In [29]:
p = np.array([[1,2,3],[-25,8,10000],[4,5,6]])


In [30]:
p


array([[    1,     2,     3],
       [  -25,     8, 10000],
       [    4,     5,     6]])

In [31]:
from sklearn.preprocessing import StandardScaler
d = StandardScaler()
p = d.fit_transform(p)

In [32]:
p # [ -3 , 3]# value - mean/std deviation

array([[ 0.58877664, -1.22474487, -0.7074251 ],
       [-1.40794413,  1.22474487,  1.41421351],
       [ 0.8191675 ,  0.        , -0.70678842]])

In [33]:
df.describe()

RowNumber    CustomerId  CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.00000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.48290     38.924392      5.012800   
std     2886.89568  7.193619e+04     96.72014     10.486738      2.892174   
min        1.00000  1.556570e+07    225.00000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.00000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.00000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    717.25000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.00000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76489.148004       1.530200      0.70550        0.515100   
std     62399.589585       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127651.035000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

In [35]:
df["Age"]

0       42.000000
1       41.000000
2       42.000000
3       39.000000
4       43.000000
5       44.000000
6       50.000000
7       38.924392
8       44.000000
9       43.000000
10      31.000000
11      24.000000
12      34.000000
13      25.000000
14      35.000000
15      45.000000
16      58.000000
17      24.000000
18      45.000000
19      24.000000
20      41.000000
21      32.000000
22      38.000000
23      46.000000
24      38.000000
25      25.000000
26      36.000000
27      44.000000
28      43.000000
29      29.000000
          ...    
9970    42.000000
9971    34.000000
9972    26.000000
9973    27.000000
9974    33.000000
9975    50.000000
9976    33.000000
9977    32.000000
9978    40.000000
9979    58.000000
9980    35.000000
9981    42.000000
9982    46.000000
9983    40.000000
9984    35.000000
9985    36.000000
9986    47.000000
9987    30.000000
9988    30.000000
9989    28.000000
9990    33.000000
9991    53.000000
9992    36.000000
9993    28.000000
9994    29

In [36]:
x_train[0:5,:]

array([[0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 6.6700000e+02, 3.4000000e+01, 5.0000000e+00,
        0.0000000e+00, 2.0000000e+00, 1.0000000e+00, 0.0000000e+00,
        1.6383064e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        1.0000000e+00, 4.2700000e+02, 4.2000000e+01, 1.0000000e+00,
        7.5681520e+04, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        5.7098000e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 5.3500000e+02, 2.9000000e+01, 2.0000000e+00,
        1.1236734e+05, 1.0000000e+00, 1.0000000e+00, 0.0000000e+00,
        1.8563076e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00,
        1.0000000e+00, 6.5400000e+02, 4.0000000e+01, 5.0000000e+00,
        1.0568363e+05, 1.0000000e+00, 1.0000000e+00, 0.0000000e+00,
        1.7361709e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        0.0000000e+0

In [37]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [38]:
x_train[0:5,:]

array([[-1.0148604 , -0.5698444 ,  1.74367544,  1.09196221, -1.09196221,
         0.17002733, -0.46475253,  0.00666099, -1.21572918,  0.8095029 ,
         0.64259497, -1.03227043,  1.10643166],
       [-1.0148604 ,  1.75486502, -0.57350122, -0.91578261,  0.91578261,
        -2.30199252,  0.30092358, -1.37744033, -0.00637674, -0.92159124,
         0.64259497,  0.9687384 , -0.74866447],
       [ 0.98535719, -0.5698444 , -0.57350122,  1.09196221, -1.09196221,
        -1.18958359, -0.94330009, -1.031415  ,  0.57984412, -0.92159124,
         0.64259497, -1.03227043,  1.48533467],
       [-1.0148604 , -0.5698444 ,  1.74367544, -0.91578261,  0.91578261,
         0.03612625,  0.10950455,  0.00666099,  0.47304181, -0.92159124,
         0.64259497, -1.03227043,  1.27652776],
       [-1.0148604 , -0.5698444 ,  1.74367544,  1.09196221, -1.09196221,
         2.05494247,  1.73656627,  1.04473698,  0.81009202,  0.8095029 ,
         0.64259497,  0.9687384 ,  0.55837842]])

In [39]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense 

In [40]:
classification = Sequential() 

In [41]:
x_train.shape

(8000, 13)

In [42]:
classification.add(Dense( units = 15 , kernel_initializer="random_uniform" , activation = "relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [43]:
classification.add(Dense( units = 30 , kernel_initializer="random_uniform" , activation = "relu"))

In [44]:
classification.add(Dense( units = 30 , kernel_initializer="random_uniform" , activation = "relu"))

In [45]:
classification.add(Dense( units = 1 , kernel_initializer="random_uniform" , activation = "sigmoid"))

In [46]:
classification.compile(optimizer = "adam",loss = "binary_crossentropy",metrics = ["accuracy"]) 

In [49]:
classification.fit(x_train,y_train , epochs = 25
                  

SyntaxError: unexpected EOF while parsing (<ipython-input-49-b9b922dd4e22>, line 2)

In [50]:
classification.fit(x_train,y_train , epochs = 25)

ValueError: Please provide as model targets either a single array or a list of arrays. You passed: y=7389    0
9275    0
2995    0
5316    0
356     0
49      0
7931    0
1523    0
7552    0
496     0
5110    0
1957    1
229     0
1738    0
7789    0
7567    1
4787    0
2607    0
3784    0
8879    0
1003    1
5676    0
4853    0
8946    0
9038    1
3042    0
8277    0
5979    0
2075    0
4482    0
       ..
755     0
8291    0
2496    0
7599    1
1871    0
2046    0
7877    1
4851    0
5072    0
2163    0
6036    0
6921    0
6216    0
537     0
9893    0
2897    0
7768    0
2222    0
2599    0
705     1
3468    0
6744    0
5874    0
4373    1
7891    0
9225    0
4859    0
3264    0
9845    0
2732    1
Name: Exited, Length: 8000, dtype: int64

In [51]:
ypred = classification.predict(x_test)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [52]:
ypred 

array([[0.50001025],
       [0.5000132 ],
       [0.50001806],
       ...,
       [0.4999952 ],
       [0.50000477],
       [0.5000026 ]], dtype=float32)

In [53]:
y_test

9394    0
898     1
2398    0
5906    0
2343    0
8225    1
5506    0
6451    0
2670    1
3497    1
1087    0
1819    0
2308    0
6084    0
3724    1
3184    1
6387    0
3728    0
2702    0
7883    0
2930    0
5988    0
4890    0
6718    0
5423    0
3213    0
3017    0
382     0
4237    0
4721    0
       ..
9236    0
1255    0
3445    0
5859    0
5450    0
5299    0
1712    0
7920    0
5194    0
1578    0
4943    0
3975    1
7134    0
5760    0
5276    0
8556    0
1624    0
4707    0
8387    0
5507    1
5581    0
7133    0
4041    0
4807    0
1774    0
1037    0
2899    0
9549    0
2740    0
6690    0
Name: Exited, Length: 2000, dtype: int64

In [54]:
import flask 

ImportError: cannot import name 'Flask' from 'flask' (C:\Users\utkar\Desktop\EXTERNSHIP IBM\flask.py)

In [55]:
from flask import flask

ImportError: cannot import name 'Flask' from 'flask' (C:\Users\utkar\Desktop\EXTERNSHIP IBM\flask.py)